name: Test Secret Access

on:
  workflow_dispatch:

jobs:
  test-secret-access:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret
        env:
          PAT: ${{ secrets.PAT }}
        run: echo $PAT
