name: Simple Push Test

on:
  workflow_dispatch:

jobs:
  push-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Make a Change
        run: echo "Testing push" >> test.txt

      - name: Commit and Push Change
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add test.txt
          git commit -m "Test commit"
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/BasselAlShaar/fullstack-repo.git
          git push origin HEAD:main
